version: '3'
services:
  db:
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres                       
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db_vol_dwh:/var/lib/postgresql/data
      - ./init_scripts/:/docker-entrypoint-initdb.d/

volumes:
  db_vol_dwh: